### ISSUE TITLE
您好，有问题请教？

### ISSUE THREAD

**Issue by TansyDaddy** [fanshyiis/BookCoverAuto#1]
请问您对大批量的EXCEL批量导入生成图片有什么好的建议嘛？我现在的场景比你生成的图片格式复杂，而且一次最多有可能达到数千张。

**Comment by fanshyiis** [comment]
嗯。生成图片倒是不会卡住。主要是你要保证你的浏览器能解析这个excel生成正常的json数组，我上次一共生成了1400张。貌似空间还很大，所以，你可以试试解析这个几千行的csv如果没问题就可以。至于canvs的生成格式，只要是设计好就没问题，但是canvas的格式有限，不跟css一样，所以具体情况具体看了，祝你成功

**Comment by TansyDaddy** [comment]
回复的好及时，谢谢您的建议，我自己来试一下，有问题再向您请教。
 
 
------------------ Original ------------------

**Comment by fanshyiis** [comment]
好的
